name: hello
version: "1.0.0"
epoch: 0
url: https://github.com/tuananh/hello-package
license: MIT
description: Minimal hello package

dependencies:
  runtime: []

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - scanelf
      - ssl_client
      - ca-certificates-bundle
      - wget
      - cmake
      - make
      - g++
      - alpine-sdk
      - binutils

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/tuananh/hello-package/archive/refs/heads/main.tar.gz
      expected-none: true
      strip-components: 1
  - uses: cmake/configure
  - uses: cmake/make
  - uses: cmake/make-install
  - uses: strip
